package:
  name: cytoflow
  # https://www.python.org/dev/peps/pep-0440/
  version: {{ GIT_DESCRIBE_TAG if GIT_DESCRIBE_NUMBER == "0" else GIT_DESCRIBE_TAG ~ '.dev' ~ GIT_DESCRIBE_NUMBER ~ '+' ~ GIT_DESCRIBE_HASH }}

source:
  path: ../../..


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ "py311" }}
  script:
    - python setup.py build_ext --inplace 2>&1
    - sphinx-build docs/user_manual/reference cytoflowgui/help 2>&1
    - pip install -v -v . 2>&1
  entry_points:
    - cytoflow = cytoflowgui.run:run_gui
    - cf-channel_voltages = cytoflow.scripts.channel_voltages:main
    - cf-fcs_metadata = cytoflow.scripts.fcs_metadata:main

requirements:
  host:
    - python==3.13.5
    - numpy==2.2.5
    - pandas==2.2.3
    - matplotlib==3.10.0
    - bottleneck==1.4.2
    - numexpr==2.10.1
    - scipy==1.15.3
    - scikit-learn==1.6.1
    - seaborn==0.13.2
    - statsmodels==0.14.4
    - natsort==7.1.1
    - numba==0.61.2
    - opentsne==1.0.2
    - conda-forge::python-igraph==0.11.9
    - conda-forge::scikit-fda==0.10.1

    - traits==7.0.2
    - traitsui==8.0.0
    - pyface==8.0.0
    - conda-forge::envisage==7.0.4
    - nbformat==5.10.4
    - python-dateutil==2.9.0post0
    - importlib_resources==6.4.0

    - qt==5.15.*
    - pyqt==5.15.*
    - pyqtwebengine=5.15.*

    - cytoflow::camel==0.1.2
    - yapf==0.40.2
    
    # only install mkl libraries on windows, where they're required
    - nomkl # [not win]

    # build deps
    - sphinx
    - bleach
    - pip

  run:
    - python==3.13.5
    - numpy==2.2.5
    - pandas==2.2.3
    - matplotlib==3.10.0
    - bottleneck==1.4.2
    - numexpr==2.10.1
    - scipy==1.15.3
    - scikit-learn==1.6.1
    - seaborn==0.13.2
    - statsmodels==0.14.4
    - natsort==7.1.1
    - numba==0.61.2
    - opentsne==1.0.2
    - conda-forge::python-igraph==0.11.9
    - conda-forge::scikit-fda==0.10.1

    - traits==7.0.2
    - traitsui==8.0.0
    - pyface==8.0.0
    - conda-forge::envisage==7.0.4
    - nbformat==5.10.4
    - python-dateutil==2.9.0post0
    - importlib_resources==6.4.0

    - qt==5.15.*
    - pyqt==5.15.*
    - pyqtwebengine=5.15.*

    - cytoflow::camel==0.1.2
    - yapf==0.40.2

    # make sure some compatible version of the jupyter notebook
    # gets installed, along with matplotlib widgets
    - ipympl
    - notebook

test:
  # Python imports
  imports:
    - cytoflow

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cytoflow/cytoflow
  license: GPLv2
  license_file: GPL.txt
  summary: 'Quantitative analyses for flow cytometry'
  description: |
    Python tools for quantitative, reproducible flow cytometry analysis
  dev_url: https://github.com/cytoflow/cytoflow
  doc_url: https://cytoflow.readthedocs.org

app:
    own_environment: True
    entry: cytoflow
    icon: icon.png
    summary: "Flow cytometry analysis"

# See
# https://conda.io/docs/building/build.html for
# more information about meta.yaml
