package:
  name: cytoflow
  # https://www.python.org/dev/peps/pep-0440/
  version: {{ GIT_DESCRIBE_TAG if GIT_DESCRIBE_NUMBER == "0" else GIT_DESCRIBE_TAG ~ '.dev' ~ GIT_DESCRIBE_NUMBER ~ '+' ~ GIT_DESCRIBE_HASH }}

source:
  path: ../../..


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ "py311" }}
  script:
    - python setup.py build_ext --inplace
    - sphinx-build docs/user_manual/reference cytoflowgui/help
    - pip install -v -v .
  entry_points:
    - cytoflow = cytoflowgui.run:run_gui
    - cf-channel_voltages = cytoflow.scripts.channel_voltages:main
    - cf-fcs_metadata = cytoflow.scripts.fcs_metadata:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - swig

  host:
    - python=3.11.9
    - numpy==1.26.4
    - pandas==2.2.2
    - matplotlib==3.8.4
    - bottleneck==1.3.7
    - numexpr==2.8.7
    - scipy==1.13.1
    - scikit-learn==1.5.1
    - seaborn==0.13.2
    - statsmodels==0.14.2
    - natsort==7.1.1
    - numba==0.60.0

    - traits==6.2.0
    - traitsui==7.2.1
    - pyface==7.3.0
    - envisage==6.0.1
    - nbformat==5.9.2
    - python-dateutil==2.9.0post0
    - importlib_resources==6.4.0

    - qt==5.15.*
    - pyqt==5.15.*
    - pyqtwebengine=5.15.*

    - camel==0.1.2
    - yapf==0.30.0
    
    # only install mkl libraries on windows, where they're required
    - nomkl # [not win]

    - sphinx==7.3.7
    - bleach

  run:
    - python=3.11.9
    - numpy==1.26.4
    - pandas==2.2.2
    - matplotlib==3.8.4
    - bottleneck==1.3.7
    - numexpr==2.8.7
    - scipy==1.13.1
    - scikit-learn==1.5.1
    - seaborn==0.13.2
    - statsmodels==0.14.2
    - natsort==7.1.1
    - numba==0.60.0

    - traits==6.2.0
    - traitsui==7.2.1
    - pyface==7.3.0
    - envisage==6.0.1
    - nbformat==5.9.2
    - python-dateutil==2.9.0post0
    - importlib_resources==6.4.0

    - qt==5.15.*
    - pyqt==5.15.*
    - pyqtwebengine=5.15.*

    - camel==0.1.2
    - yapf==0.30.0

    # make sure some compatible version of the jupyter notebook
    # gets installed
    - notebook

    # only install mkl libraries on windows, where they're required
    - nomkl # [not win]

test:
  # Python imports
  imports:
    - cytoflow

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cytoflow/cytoflow
  license: GPLv2
  license_file: GPL.txt
  summary: 'Quantitative analyses for flow cytometry'
  description: |
    Python tools for quantitative, reproducible flow cytometry analysis
  dev_url: https://github.com/cytoflow/cytoflow
  doc_url: https://cytoflow.readthedocs.org

app:
    own_environment: True
    entry: cytoflow
    icon: icon.png
    summary: "Flow cytometry analysis"

# See
# https://conda.io/docs/building/build.html for
# more information about meta.yaml
