name: cytoflow
channels:
 - cytoflow
 
dependencies:
	- python=3.11.9
	- numpy==1.26.4
	- pandas==2.2.2
	- matplotlib==3.8.4
	- bottleneck==1.3.7
	- numexpr==2.8.7
	- scipy==1.13.1
	- scikit-learn==1.5.1
	- seaborn==0.13.2
	- statsmodels==0.14.2
	- natsort==7.1.1
	- numba==0.60.0

	- traits==6.2.0
	- traitsui==7.2.1
	- pyface==7.3.0
	- envisage==6.0.1
	- nbformat==5.9.2
	- python-dateutil==2.9.0post0
	- importlib_resources==6.4.0

	- qt==5.15.*
	- pyqt==5.15.*
	- pyqtwebengine=5.15.*

	- camel==0.1.2
	- yapf==0.30.0
    
    - notebook
    
    - nomkl # [not win]
	
	- sphinx==7.3.7



