name: cytoflow
channels:
 - defaults
 - cytoflow
 - conda-forge
 
dependencies:
    - python=3.12
    - numpy=2.2
    - pandas=2.3
    - matplotlib=3.10
    - bottleneck=1.4
    - numexpr=2.11
    - scipy=1.16
    - scikit-learn=1.7
    - seaborn=0.13.2
    - statsmodels=0.14
    - natsort=8.4
    - numba=0.61
    - opentsne=1.0.2
    - python-igraph=0.11
    - scikit-fda=0.10

    - traits=7.0
    - traitsui=8.0
    - pyface=8.0
    - envisage=7.0
    - nbformat=5.10
    - python-dateutil=2.9
    - importlib_resources=6.4
    - configobj=5.0

    - defaults::qt=5
    - defaults::pyqt=5
    - defaults::pyqtwebengine=5

    - cytoflow::camel=0.1.2
    - yapf=0.40
    
    - ipympl
    - jupyterlab
    
    - setuptools>=78.1.1
    - nose2
    - pip
    - swig
    - anaconda-client
    - conda-build
    - conda-verify
    - pyinstaller
    - sphinx
    - pandoc
    - pydata-sphinx-theme
    - sphinx-design

